development:
  adapter: postgresql
  encoding: unicode
  database: scheduler_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: hunter
test:
  adapter: postgresql
  encoding: unicode
  database: scheduler_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: hunter

production:
  adapter: postgresql
  encoding: unicode
  database: scheduler_production
  pool: 5
  password:
